// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY6jGtK_JlR-foYayF-8PS_44kJ_Y_0L4',
    appId: '1:1983638353:ios:30069c8afee759c1930170',
    messagingSenderId: '1983638353',
    projectId: 'maxapp-7dc7b',
    storageBucket: 'maxapp-7dc7b.appspot.com',
    iosBundleId: 'com.example.maxapp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcplhDFlPWY5v6hRBZ8MkRffrDslDAwV0',
    appId: '1:1983638353:android:5b2c09437751646a930170',
    messagingSenderId: '1983638353',
    projectId: 'maxapp-7dc7b',
    storageBucket: 'maxapp-7dc7b.appspot.com',
  );

}